# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ab45eec14f394fc748b7ddba8ffa7c6bdfc5d7a1d6186b2ea44cffdc615bc88c58fc5bcc90625f9c04b4c57f64c73716e6bd907c2274779cffc05e6baff3b3

test:
  secret_key_base: 7a425f12e5b2c671a26d2550adbac6ac6b6e36aa2c407d315e1b6d5b34167ebf8e1b7d52a83444672f5dc3e061189dbd508362992c75bfba0cafa3bdbf78fb19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
